services:
  portfolio:
    container_name: merten-portfolio
    image: mertend/portfolio:latest
    networks:
      - web
    restart: unless-stopped
    volumes:
      - portfolio-data:/data
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - AI_MODEL=${AI_MODEL}
      - DATABASE_URL=file:/data/portfolio.db
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - com.centurylinklabs.watchtower.enable=true

      - traefik.http.middlewares.redirect-merten-portfolio.redirectregex.regex=^https?://mertendieckmann.de/(.*)
      - traefik.http.middlewares.redirect-merten-portfolio.redirectregex.replacement=https://merten.tech/$${1}
      - traefik.http.middlewares.redirect-merten-portfolio.redirectregex.permanent=true

      - traefik.http.routers.merten-portfolio.rule=Host(`mertendieckmann.de`) || Host(`merten.tech`)
      - traefik.http.routers.merten-portfolio.entrypoints=websecure
      - traefik.http.routers.merten-portfolio.tls=true
      - traefik.http.routers.merten-portfolio.tls.certresolver=le-merten
      - traefik.http.routers.merten-portfolio.middlewares=redirect-merten-portfolio

      - traefik.http.middlewares.admin-auth.basicauth.users=${ADMIN_BASIC_AUTH}

      - traefik.http.routers.merten-portfolio-admin.rule=(Host(`mertendieckmann.de`) || Host(`merten.tech`)) && PathPrefix(`/admin`)
      - traefik.http.routers.merten-portfolio-admin.entrypoints=websecure
      - traefik.http.routers.merten-portfolio-admin.tls=true
      - traefik.http.routers.merten-portfolio-admin.tls.certresolver=le-merten
      - traefik.http.routers.merten-portfolio-admin.middlewares=redirect-merten-portfolio,admin-auth

volumes:
  portfolio-data:

networks:
  web:
    external: true
