export const chatLoadingPhrases = [
  "Marinating",
  "Doing",
  "Channeling",
  "Using my powers",
  "Waddling around",
  "Staring into the void",
  "Vibing",
  "Overthinking",
  "Trying my best",
  "Contemplating existence",
  "Pretending to work",
  "Twiddling thumbs",
  "Getting distracted",
  "Taking a lil nap",
  "Doing math or something",
  "Cooking up something good",
  "Brewing a masterpiece",
  "Connecting the brain cells",
  "Gathering inspiration",
  "Sprinkling fairy dust",
  "Entering the flow state",
  "Leveling up",
  "Buffering brilliance",
  "Watering my fish",
  "Consulting the magic 8 ball",
  "Looking for my glasses",
  "Counting digital sheep",
  "Untangling the web",
  "Polishing the pixels",
  "Searching for snacks",
  "Warming up the servers"
]